import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Admin',
      email: 'admin@admin.com',
      password: bcrypt.hashSync('admin123'),
      isAdmin: true,
    },
    {
      name: 'John Doe',
      email: 'john@example.com',
      password: bcrypt.hashSync('user123'),
      isAdmin: false,
    },
    {
      name: 'Jane Smith',
      email: 'jane@example.com',
      password: bcrypt.hashSync('user123'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Classic White Shirt',
      slug: 'classic-white-shirt',
      category: 'Shirts',
      image: '/images/banner/banner1.webp',
      price: 49.99,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 24,
      countInStock: 15,
      description:
        'A timeless classic white shirt perfect for any occasion. Made from premium cotton fabric, this shirt offers comfort and style. Perfect for both casual and formal wear.',
      isFeatured: true,
      banner: '/images/banner/banner1.webp',
    },
    {
      name: 'Slim Fit Blue Shirt',
      slug: 'slim-fit-blue-shirt',
      category: 'Shirts',
      image: '/images/banner/banner2.webp',
      price: 59.99,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 18,
      countInStock: 12,
      description:
        'Modern slim-fit blue shirt with a contemporary design. This shirt features a comfortable fit and high-quality material that maintains its shape wash after wash.',
      isFeatured: true,
      banner: '/images/banner/banner2.webp',
    },
    {
      name: 'Casual Black Shirt',
      slug: 'casual-black-shirt',
      category: 'Shirts',
      image: '/images/banner/banner1.webp',
      price: 54.99,
      brand: 'Puma',
      rating: 4.0,
      numReviews: 15,
      countInStock: 20,
      description:
        'Versatile black shirt that pairs well with any outfit. Made from breathable fabric, it keeps you comfortable throughout the day.',
      isFeatured: false,
    },
    {
      name: 'Premium Denim Jeans',
      slug: 'premium-denim-jeans',
      category: 'Pants',
      image: '/images/banner/banner2.webp',
      price: 79.99,
      brand: 'Levi\'s',
      rating: 4.7,
      numReviews: 32,
      countInStock: 18,
      description:
        'High-quality denim jeans with a perfect fit. These jeans are durable, comfortable, and stylish. Available in classic blue wash that never goes out of style.',
      isFeatured: true,
      banner: '/images/banner/banner1.webp',
    },
    {
      name: 'Slim Fit Chino Pants',
      slug: 'slim-fit-chino-pants',
      category: 'Pants',
      image: '/images/banner/banner2.webp',
      price: 64.99,
      brand: 'Zara',
      rating: 4.3,
      numReviews: 21,
      countInStock: 14,
      description:
        'Smart and stylish chino pants perfect for both office and casual settings. Made from premium cotton twill, these pants offer comfort and elegance.',
      isFeatured: false,
    },
    {
      name: 'Cargo Pants',
      slug: 'cargo-pants',
      category: 'Pants',
      image: '/images/banner/banner1.webp',
      price: 69.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 19,
      countInStock: 16,
      description:
        'Functional cargo pants with multiple pockets. Perfect for outdoor activities and casual wear. Made from durable material that withstands daily wear.',
      isFeatured: false,
    },
    {
      name: 'Leather Handbag',
      slug: 'leather-handbag',
      category: 'Handbags',
      image: '/images/banner/banner2.webp',
      price: 129.99,
      brand: 'Coach',
      rating: 4.6,
      numReviews: 28,
      countInStock: 10,
      description:
        'Elegant leather handbag with spacious interior. Made from genuine leather, this handbag combines style and functionality. Perfect for everyday use.',
      isFeatured: true,
      banner: '/images/banner/banner2.webp',
    },
    {
      name: 'Designer Tote Bag',
      slug: 'designer-tote-bag',
      category: 'Handbags',
      image: '/images/banner/banner1.webp',
      price: 89.99,
      brand: 'Michael Kors',
      rating: 4.4,
      numReviews: 22,
      countInStock: 13,
      description:
        'Stylish tote bag with modern design. Features multiple compartments for organized storage. Made from high-quality materials for long-lasting use.',
      isFeatured: false,
    },
    {
      name: 'Crossbody Bag',
      slug: 'crossbody-bag',
      category: 'Handbags',
      image: '/images/banner/banner2.webp',
      price: 74.99,
      brand: 'Kate Spade',
      rating: 4.5,
      numReviews: 16,
      countInStock: 11,
      description:
        'Compact crossbody bag perfect for carrying essentials. Features adjustable strap and multiple interior pockets. Ideal for casual outings.',
      isFeatured: false,
    },
    {
      name: 'Sporty T-Shirt',
      slug: 'sporty-t-shirt',
      category: 'Shirts',
      image: '/images/banner/banner1.webp',
      price: 34.99,
      brand: 'Under Armour',
      rating: 4.8,
      numReviews: 45,
      countInStock: 25,
      description:
        'Performance t-shirt made for active lifestyle. Moisture-wicking fabric keeps you dry and comfortable during workouts and daily activities.',
      isFeatured: false,
    },
  ],
};

export default data;
